### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg'

### ISSUE THREAD

**Issue by Zhr1110** [ZK-Zhou/spikformer#1]
I'm so sorry to bother you. I encountered the above problem when creating model. I want to know what may be the reason. Is it because of Timm's version?

**Comment by ZK-Zhou** [comment]
yes，timm&nbsp;version&nbsp;is 0.5.4


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZK-Zhou/spikformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 下午5:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZK-Zhou/spikformer] TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg' (Issue #1)





 
I'm so sorry to bother you. I encountered the above problem when creating model. I want to know what may be the reason. Is it because of Timm's version?

**Comment by Zhr1110** [comment]
The problem has been solved. Thank you very much!


自由魂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZK-Zhou/spikformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月8日(星期六) 下午5:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ZK-Zhou/spikformer] TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg' (Issue #1)





 yes，timm&amp;nbsp;version&amp;nbsp;is 0.5.4 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "ZK-Zhou/spikformer"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年10月8日(星期六) 下午5:16 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[ZK-Zhou/spikformer] TypeError: __init__() got an unexpected keyword argument 'pretrained_cfg' (Issue #1) 
 
 
 
 
 
   
 I'm so sorry to bother you. I encountered the above problem when creating model. I want to know what may be the reason. Is it because of Timm's version?

**Comment by ZK-Zhou** [comment]
yes，the version of timm we used is 0.5.4
